version: "3.8"

services:
  app:
    build: .
    container_name: go_url_shortener_app
    ports:
      - "1232:1232"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    command: ["-listenaddr", "${LISTENADDR}"]
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:16-alpine
    container_name: go_url_shortener_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
volumes:
  postgres-data: