package types

import (
	"encoding/json"
	"net/http"
	"sync"

	"github.com/sqids/sqids-go"
)

var (
	counter    = NewGlobalCounter()
	APIVersion = "v1" // API version for the URL shortener service
)

// ContextKey is a type used for keys in the context.
type ContextKey string

// Payload represents the structure of the JSON payload expected in requests.
// It contains the short URL and the long URL.
type Payload struct {
	ShortURL string `json:"ShortURL"`
	LongURL  string `json:"LongURL"`
}

// GlobalCounter is a thread-safe counter that can be used to generate unique IDs.
// It uses a mutex to ensure that increments and reads are safe in a concurrent environment.
// The counter starts at 0 and increments by 1 each time Increment or GetAndIncrement is called.
// The Count method returns the current value of the counter without incrementing it.
// The GetAndIncrement method returns the current value and then increments the counter.
// This is useful for generating unique identifiers in a concurrent application.
type GlobalCounter struct {
	mu    sync.Mutex
	count uint64
}

// Increment increases the counter by 1 in a thread-safe manner.
func (c *GlobalCounter) Increment() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.count++
}

// Count returns the current value of the counter without incrementing it.
// It locks the mutex to ensure thread safety while reading the value.
func (c *GlobalCounter) Count() uint64 {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.count
}

// GetAndIncrement returns the current value of the counter and increments it by 1.
// This method is also thread-safe, ensuring that the value returned is consistent
// even in a concurrent environment
func (c *GlobalCounter) GetAndIncrement() uint64 {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.count++
	return c.count
}

// NewGlobalCounter creates a new instance of GlobalCounter.
// It initializes the count to 0 and returns a pointer to the new instance.
func NewGlobalCounter() *GlobalCounter {
	return &GlobalCounter{
		count: 0,
	}
}

// sqidsGen is a generator for unique IDs using the sqids package.
type SqidsGen struct {
	Sqid *sqids.Sqids
}

// NewSqidsGen creates a new instance of sqidsGen.
func NewSqidsGen() *SqidsGen {
	squid, _ := sqids.New()
	sqidsGen := &SqidsGen{
		Sqid: squid,
	}
	return sqidsGen
}

// Generate creates a new unique ID using the sqids package.
// It uses the global counter to ensure that each ID is unique.
// The ID is generated by encoding the current value of the counter into a string format.
// The counter is incremented after generating the ID
func (s *SqidsGen) Generate() string {
	id, _ := s.Sqid.Encode([]uint64{counter.GetAndIncrement()})
	return id
}

// DecodePayload decodes the JSON payload from the request body
func DecodePayload(r *http.Request) (*Payload, error) {
	var payload Payload
	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		return nil, NewBadRequestError([]Details{
			{Field: "body", Issue: "Invalid JSON format"},
		})
	}
	return &payload, nil
}
